### ISSUE TITLE
Outliers in principal component returned by `pca_poisson_residuals`

### ISSUE THREAD

**Issue by tomsing1** [rafalab/smallcount#2]
Thanks a lot for making this R package available! I have tried it on a number of datasets, and the speed-up compared to the sequential calling of `scry::nullResiduals` and `BiocSingular::runPCA` is impressive.

One dataset produced an unexpected result, so I thought I'd share my observation in case it's useful to you.

### Context
I am looking at sizable dataset of single-nuclei RNA-seq counts. Nuclei from 34 tissue samples were analyzed using the 10X Genomics platform, each in a separate channel. After removal of empty droplets and QC filtering, performed separately for each of the 34 single-sample count matrices, I combined the raw counts into a single sparse matrix `m` (14477  genes x 181880 cells).

I identified the top 1000 genes with the highest deviance using scry, providing a factor indicating the sample of origin as the `batch` covariate. (I noticed the `poisson_deviance` function in the `smallcount` package, but opted for the `scry` implementation because it allowed me to specify the covariate. The `poisson_deviance` function yields highly similar results.)

```r
deviances <- scry::devianceFeatureSelection(
  m,
  batch = samples,
  fam = "binomial")
names(deviances) <- row.names(m)
keep <- head(row.names(m)[order(deviances, decreasing = TRUE)], 1e3)
```

Some of the deviances are extremely large:

```r
> summary(deviances)
    Min.  1st Qu.   Median     Mean  3rd Qu.     Max.     NA's 
    2112    20524    46459    68469    88400 10298937       12 

 hist(log10(deviances), breaks = 50)
```

![deviance_hist](https://user-images.githubusercontent.com/10490984/118433647-4db22b00-b690-11eb-9dd0-d0ea5cb68302.png)

Then I ran the `pca_poisson_residuals` function

```r
pc <- pca_poisson_residuals(m[keep, ])
```

and examined the returned PCs. I noticed that PC3 seems to be skewed by a small number of very high values:

```r
> summary(pc$x[, 3])
    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
 -9.0522  -2.6542  -0.3945   0.3933   1.5268 847.4401 
```

![PC_histograms](https://user-images.githubusercontent.com/10490984/118432793-5efa3800-b68e-11eb-8522-3f75fa67300d.png)

Perhaps this useful information to you? 

Maybe I need to filter the high-deviance genes first? Or perhaps the `pca_poisson_residuals` could make use of arguments analogous to prcomp's `center` and / or  `scale.`? (I typically set `center = TRUE` and `scale = TRUE` when passing Pearson residuals into the `BiocSingular::runPCA` function, that made me wonder...)

Thanks a lot for sharing your work with the single-cell community!

**Comment by rafalab** [comment]
Thanks for the report. Note you should use poisson instead of binomial in your call to scry::devianceFeatureSelection.  But I doubt that explains your heavy tailed third PC. I have seen this behavior before caused by genes with outliers. Specifically, genes with mostly 0s counts and then 1 or more much larger ones. Note, for example, that the Peasson residuals for the 5 in a gene with 999 0s and one 5 is `(5- 0.01) / 0.1` which is almost 50. PCA is expected data that, after scaling, is about normal 0,1 so a 50 really throws it off.

I would filter out these genes first and try again.

**Comment by tomsing1** [comment]
Thanks a lot for pointing out my error in using the wrong distribution - and for pointing out the problems outliers can cause. Much appreciated.
