### ISSUE TITLE
Missing import from the RSpectra R package?

### ISSUE THREAD

**Issue by tomsing1** [rafalab/smallcount#4]
I ran into an error in the `pca_poisson_residuals` because the `RSpectra` package wasn't available. It seems the `eigs_sym` function from this package is used but not noted as an import/dependency. Perhaps it needs to be added?

https://github.com/rafalab/smallcount/blob/6a29f21ec07d8da9688ec05e82b21370dad38454/R/pca_poisson_residuals.R#L39

**Comment by rafalab** [comment]
Added. Thanks.
